### ISSUE TITLE
Google drive link for pretrained weights

### ISSUE THREAD

**Issue by hrishikeshps94** [GlassyWu/AECR-Net#27]
Is there any way I can get the google drive link of the pretrained weights.

**Comment by cherrysherryplus** [comment]
> Is there any way I can get the google drive link of the pretrained weights.

https://drive.google.com/drive/folders/1fPordZAKT8nF-jhz8VrLjBlCogDuriAj?usp=sharing

**Comment by hrishikeshps94** [comment]
Thank you
